# Generated by Django 4.2.3 on 2023-07-28 05:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stadium', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('lname', models.CharField(default='', max_length=100)),
                ('date_of_birth', models.DateField(default=datetime.datetime.now)),
                ('address', models.CharField(max_length=150)),
                ('contact', models.CharField(default='', max_length=30)),
                ('email', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, upload_to='User_photo/%Y/%m/%d')),
            ],
            options={
                'db_table': 'user_model',
            },
        ),
        migrations.CreateModel(
            name='BronStadiumModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.datetime.now)),
                ('end_date', models.DateField(default=datetime.datetime.now)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stadium.stadiummodel')),
            ],
            options={
                'db_table': 'bron_stadium_model',
            },
        ),
    ]
