# Generated by Django 4.2.3 on 2023-07-28 05:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BronedStadiumModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'broned_stadium_model',
            },
        ),
        migrations.CreateModel(
            name='OwnerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('lname', models.CharField(default='', max_length=100)),
                ('date_of_birth', models.DateField(default=datetime.datetime.now)),
                ('address', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'stadium_owner_model',
            },
        ),
        migrations.CreateModel(
            name='StadiumModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=500)),
                ('contact', models.CharField(default='', max_length=30)),
                ('price1hour', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stadium.ownermodel')),
            ],
            options={
                'db_table': 'stadium_model',
            },
        ),
    ]
