# Generated by Django 4.2.3 on 2023-07-28 11:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stadium', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingmodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 28, 16, 13, 44, 229)),
        ),
    ]
